### ISSUE TITLE
Heading: Top 3 things  (Helm PHR project)- swap from qewdDB to openEHR

### ISSUE THREAD

**Issue by tony-shannon** [QEWD-Courier/Arc-QEWD-Courier-hive#13]
FYI @robtweed 

Top 3 things swap API from qewdDB to openEHR
https://github.com/RippleOSI/Ripple-openEHR/commit/00081dbfec97ce62d65501edca2297a60ee76a2b

To do , at some point that suits please

**Comment by robtweed** [comment]
Switching to using the OpenEHR template for Top3Issues (https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/Top%203%20issues/top_3_issues.md  plus an AQL change by Ian) proved to still be problematic - appears it may be a residual EtherCIS problem handling the template, so may require investigation by Christian.  

Saving a Top3Things record appears to work, but on retrieval only the 1st of the Top3Things is returned 

For now, we probably need to continue using the QEWD/YottaDB implementation of Top3Things

**Comment by robtweed** [comment]
Here's the logs:  first saving a Top3Things record using Flat JSON on EtherCIS system at http://46.101.81.30:8080:

{
  "host": "ethercis",
  "url": "/rest/v1/composition",
  "queryString": {
    "templateId": "IDCR - Top issues.v0",
    "ehrId": "a9b05c5b-6727-4535-adeb-04b015c516a6",
    "format": "FLAT"
  },
  "method": "POST",
  "session": "sessionId:127.0.0.1-guest-1551280880201-855290578-1114",
  "options": {
    "body": {
      "ctx/composer_name": "Patient",
      "ctx/health_care_facility|id": "999999-345",
      "ctx/health_care_facility|name": "Home",
      "ctx/id_namespace": "NHS-UK",
      "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
      "ctx/language": "en",
      "ctx/territory": "GB",
      "ctx/time": "2019-02-27T15:22:17Z",
      "top_issues/story_history:0/issue_1/issue_1_name": "Anxiety",
      "top_issues/story_history:0/issue_1/issue_1_detail": "I worry about work",
      "top_issues/story_history:0/issue_2/issue_2_name": "Tinitus",
      "top_issues/story_history:0/issue_2/issue_2_detail": "Keeps me awake at night",
      "top_issues/story_history:0/issue_3/issue_3_name": "To be completed",
      "top_issues/story_history:0/issue_3/issue_3_detail": "To be completed"
    }
  }
}

*** postHeading response: {"data":{"compositionUid":"c796aa3e-ba56-4333-b374-0f5c7196f071::ethercis.ripple.org::1","meta":{"href":"rest/v1/composition?uid=c796aa3e-ba56-4333-b374-0f5c7196f071::ethercis.ripple.org::1"},"action":"CREATE"}}

Then retrieval:

{
  "executedAQL": " select     a/uid/value as uid,     a/composer/name as author,     a/context/start_time/value as date_created, \tb_a/items[at0001, 'Issue 1 Name']/value/value as Issue_1_Name,     b_a/items[at0002, 'Issue 1 Detail']/value/value as Issue_1_Detail,     b_a/items[at0001, 'Issue 2 Name']/value/value as Issue_2_Name,     b_a/items[at0002, 'Issue 2 Detail']/value/value as Issue_2_Detail,     b_a/items[at0001, 'Issue 3 Name']/value/value as Issue_3_Name,     b_a/items[at0002, 'Issue 3 Detail']/value/value as Issue_3_Detail from EHR e[ehr_id/value='a9b05c5b-6727-4535-adeb-04b015c516a6'] contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] contains OBSERVATION B[openEHR-EHR-OBSERVATION.story.v1] contains CLUSTER b_a[openEHR-EHR-CLUSTER.issue.v0] where a/name/value='Top issues'",
  "resultSet": [
    {
      "uid": "c796aa3e-ba56-4333-b374-0f5c7196f071::ethercis.ripple.org::1",
      "Issue_1_Detail": "I worry about work",
      "Issue_2_Detail": null,
      "Issue_1_Name": "Anxiety",
      "Issue_3_Detail": null,
      "author": "Patient",
      "date_created": "2019-02-27T15:22:17Z",
      "Issue_3_Name": null,
      "Issue_2_Name": null
    }
  ]
}

**Comment by PhilBarrett** [comment]
@freshehr - could you take a look at this please in christian's absence?

**Comment by freshehr** [comment]
This seems to work correctly

```
select
    a/uid/value as uid,
    a/composer/name as author,
    a/context/start_time/value as date_created,
  b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 1']/items[at0001]/value/value as Issue_1_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 1']/items[at0002]/value/value as Issue_1_Detail,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 2']/items[at0001]/value/value as Issue_2_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 2']/items[at0002]/value/value as Issue_2_Detail,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 3']/items[at0001]/value/value as Issue_3_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 3']/items[at0002]/value/value as Issue_3_Detail
from EHR e[ehr_id/value='{{ehrId}}']
contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1]
contains CLUSTER b_a[openEHR-EHR-CLUSTER.issue.v0]
where a/name/value='Top issues'
```

**Comment by robtweed** [comment]
Current status - Ian suggested this AQL instead for fetching Top3Things:

select
    a/uid/value as uid,
    a/composer/name as author,
    a/context/start_time/value as date_created,
  b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 1']/items[at0001]/value/value as Issue_1_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 1']/items[at0002]/value/value as Issue_1_Detail,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 2']/items[at0001]/value/value as Issue_2_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 2']/items[at0002]/value/value as Issue_2_Detail,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 3']/items[at0001]/value/value as Issue_3_Name,
    b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue 3']/items[at0002]/value/value as Issue_3_Detail
from EHR e[ehr_id/value='{{ehrId}}']
contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1]
contains CLUSTER b_a[openEHR-EHR-CLUSTER.issue.v0]
where a/name/value='Top issues'

However this is causing an EtherCIS error:

  "statusCode": 500,
  "headers": {
    "connection": "close",
    "x-error-code": "internal.unknown",
    "x-error-message": "#1.0.0 Invocation exception to method:queryInline:java.lang.IllegalArgumentException: Identifier is not defined in FROM/CONTAIN clause:b",
    "cache-control": "must-revalidate,no-cache,no-store",
    "server": "Jetty(9.4.z-SNAPSHOT)"
  },

**Comment by freshehr** [comment]
I'm geting a 404 at the Github link.
The AQL is working fine at the Ethercis instance I am working against

http://178.62.71.220:8080


{
    "executedAQL": "select     a/uid/value as uid,     a/composer/name as
author,     a/context/start_time/value as date_created,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
1']/items[at0001]/value/value as Issue_1_Name,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
1']/items[at0002]/value/value as Issue_1_Detail,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
2']/items[at0001]/value/value as Issue_2_Name,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
2']/items[at0002]/value/value as Issue_2_Detail,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
3']/items[at0001]/value/value as Issue_3_Name,
 b/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.issue.v0,'Issue
3']/items[at0002]/value/value as Issue_3_Detail from EHR e contains
COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] contains OBSERVATION
b[openEHR-EHR-OBSERVATION.story.v1] where a/name/value='Top issues'",
    "resultSet": [
        {
            "uid": "c06b5b7e-18b1-4d06-8069-557005724217::vm01.ethercis.org:
:1",
            "Issue_1_Detail": "I feel very anxious all the time",
            "Issue_2_Detail": "I wake up in the middle of the night and
can't get back to sleep",
            "Issue_1_Name": "Anxiety",
            "Issue_3_Detail": "I don't like my food as much as I used to",
            "author": "Hildi McNicoll",
            "date_created": "2017-05-23T23:11:02+02:00",
            "Issue_3_Name": "No appetite",
            "Issue_2_Name": "Not sleeping"
        },
        {
            "uid": "b477ac23-7c41-4d23-8f29-c1a5d08d46d4::vm01.ethercis.org:
:1",
            "Issue_1_Detail": "I get worried all the time",
            "Issue_2_Detail": "I seem to have lost my appetite",
            "Issue_1_Name": "Anxiety",
            "Issue_3_Detail": "I am under a lot of stress",
            "author": "Patient",
            "date_created": "2018-10-23T09:17:26+01:00",
            "Issue_3_Name": "Stress",
            "Issue_2_Name": "Appetite"
        }
    ]
}

Dr Ian McNicoll
mobile +44 (0)775 209 7859
office +44 (0)1536 414994
skype: ianmcnicoll
email: ian@freshehr.com
twitter: @ianmcnicoll


Co-Chair, openEHR Foundation ian.mcnicoll@openehr.org
Director, freshEHR Clinical Informatics Ltd.
Director, HANDIHealth CIC
Hon. Senior Research Associate, CHIME, UCL

**Comment by tony-shannon** [comment]
Please continue the discussion of this issue in the relevant project Helm PHR
https://github.com/LeedsCC/Helm-PHR-Project/issues/1
