### ISSUE TITLE
Question about naming?

### ISSUE THREAD

**Issue by killmenot** [QEWD-Courier/Arc-QEWD-Courier-hive#20]
Hi @robtweed @tony-shannon 

How the following can be possible? 
https://github.com/RippleOSI/QEWD-Courier/blob/f6b93c93cecfadb86b7f10a59e0844380298fbd3/openid-connect-server/modules/qewd-openid-connect/lib/account.js#L41-L52

Same name (prop and method) is not allowed. I recommend to rename prop to `_claims`

**Comment by robtweed** [comment]
Not sure but it currently doesn't cause any problems so I don't want to touch it
