### ISSUE TITLE
Integration Testing - need access to FHIR APIs

### ISSUE THREAD

**Issue by tony-shannon** [QEWD-Courier/Arc-QEWD-Courier-hive#29]
Dima needs access to FHIR API for patients

**Comment by robtweed** [comment]
FHIR APIs? The Discovery data you mean?
Are you trying to test the Discovery REST APIs in isolation? If so, the test NHS Numbers provided by DDS that we use for mapping to Helm patient Ids are listed here:

https://github.com/QEWD-Courier/QEWD-Courier/blob/master/cdr-service-discovery/modules/ripple-cdr-discovery/src/mapToDiscoveryNHSNo.js

Rob

**Comment by DmitrySolyannik** [comment]
Hello @robtweed , no I am talking about this one https://github.com/QEWD-Courier/QEWD-Courier/blob/master/cdr-service-discovery/modules/ripple-cdr-discovery/src/getPatientsByNHSNumber.js#L53
If I am not mistaken , I should get all patients by NHS number and then cash their data?

**Comment by robtweed** [comment]
To be clear about this - the APIs you are looking at are the Helm interfaces to the DDS APIs.  Here are the details of the DDS APIs: https://deveds.endeavourhealth.net/eds-api/
